---
name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: choice
        options:
          - lint-and-test
          - release
        description: Choose the workflow to run
        default: lint-and-test
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  python-lint-and-scan:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint-and-test')
    uses: dceoy/gh-actions-for-devops/.github/workflows/python-package-lint-and-scan.yml@main
    with:
      package-path: .
      python-version: 3.x
  python-test:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint-and-test')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Set up uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b  # v7.3.0
      - name: Install the package
        run: >
          uv sync
      - name: Test commands
        run: |
          uv run tifft --version
          uv run tifft --help
          uv run tifft history --output-csv=fred.csv DJIA SP500 NASDAQ100
          uv run tifft macd --output-csv=macd.csv SP500
          uv run tifft bb --output-csv=bb.csv SP500
          uv run tifft rsi --output-csv=rsi.csv SP500
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - python-lint-and-scan
      - python-test
    uses: dceoy/gh-actions-for-devops/.github/workflows/dependabot-auto-merge.yml@main
    permissions:
      contents: write
      pull-requests: write
      actions: read
    with:
      unconditional: true
  python-package-release:
    if: >
      github.event_name == 'push'
      || (
        github.event_name == 'workflow_dispatch'
        && (inputs.workflow == 'release' || inputs.workflow == 'lint-and-test')
      )
    uses: dceoy/gh-actions-for-devops/.github/workflows/python-package-release-on-pypi-and-github.yml@main
    permissions:
      contents: write
      id-token: write
    with:
      package-path: .
      create-releases: ${{ github.event_name == 'workflow_dispatch' && inputs.workflow == 'release' }}
      python-version: 3.x
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
